### ISSUE TITLE
Frontend | Tela de mapa

### ISSUE THREAD

**Issue by ryanolivrdev** [geta-org/sex-adapt-mobile#30]
## Overview
 - Criação da tela de mapa da aplicação.

## TO-DO
- [x] Pesquisar biblioteca para mapas no React Native.
- [x] Pesquisar sobre como fazer a lógica. 
- [x] Pesquisar sobre melhor jeito de fazer os "PINS" 
- [x] Criar o mapa.
- [x] Fazer marcador de localização do Usuário.
- [x] Fazer marcador de localização do Motel.
- [x] Fazer card de informações do Motel.
